services:
  jupyter:
    build:
      context: .
      args:
        JUPYTER_IMAGE_VERSION: latest
        JUPYTER_USER: ${JUPYTER_USER:-jupyter_user}
    ports:
      - "8888:8888"
    volumes:
      - ./data:/home/${JUPYTER_USER:-jupyter_user}/work
    environment:
      - JUPYTER_ENABLE_LAB=yes