services:
  jupyter:
    build:
      context: .
      args:
        JUPYTER_IMAGE_VERSION: latest
    ports:
      - "8888:8888"
    volumes:
      - jupyterlab-user-data:/home/jovyan
    environment:
      - JUPYTER_ENABLE_LAB=yes

volumes:
  jupyterlab-user-data:
    name: jupyterlab-user-data