services:
  jupyter:
    build:
      context: .
      args:
        JUPYTER_IMAGE_VERSION: latest
    user: root
    ports:
      - "8888:8888"
    volumes:
      - jupyterlab-user-data:/home/chiqors
    environment:
      - NB_USER=chiqors
      - CHOWN_HOME=yes
      - GRANT_SUDO=yes

volumes:
  jupyterlab-user-data:
    name: jupyterlab-user-data